theme: jekyll-theme-cayman
title: Miroir Covid 19
description: Ce site héberge une copie des informations du site du Ministère de l'Intérieur, si celui-ci est inaccessible.
show_downloads: true
links:
  - pdf:
    text: Télécharger l'attestation de déplacement dérogatoire
    url: https://github.com/leoboyerbx/covid-mirror/raw/master/Attestation_de_deplacement_derogatoire.pdf
  - source:
    text: Site du ministère
    url: https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-derogatoire
  - info:
    text: Informations officielles sur le virus
    url: https://www.gouvernement.fr/info-coronavirus
